"""Tests for the degeneracy guard (D-011).

This guard exists because EXP-001 showed that maximizing F1 on a balanced corpus with a weak
classifier produces a "flag everything" threshold, and that this artifact was concentrated in
exactly the low-resource languages the study exists to serve. These tests reproduce the
pilot's mechanism from first principles, so the guard cannot regress silently.
"""

from __future__ import annotations

import numpy as np
import pytest

from src.eval.metrics import operating_point
from src.eval.thresholds import (
    DEGENERATE_PPR_HIGH,
    is_degenerate,
    predicted_positive_rate,
    tune_threshold,
)


def test_flag_everything_is_degenerate():
    scores = np.linspace(0.1, 0.9, 100)
    assert is_degenerate(scores, 0.0)          # flags 100%
    assert predicted_positive_rate(scores, 0.0) == pytest.approx(1.0)


def test_flag_nothing_is_degenerate():
    scores = np.linspace(0.1, 0.9, 100)
    assert is_degenerate(scores, 1.0)          # flags 0%


def test_reasonable_threshold_is_not_degenerate():
    scores = np.linspace(0.0, 1.0, 100)
    assert not is_degenerate(scores, 0.5)


def test_empty_scores_are_degenerate():
    """An empty score array cannot define an operating point; treat it as degenerate rather
    than letting a downstream mean silently swallow it."""
    assert is_degenerate(np.array([]), 0.5)


def test_reproduces_the_pilot_artifact_on_balanced_data_with_a_useless_model():
    """The EXP-001 mechanism, reconstructed from first principles.

    With a classifier carrying almost no signal and a 50/50 corpus, the F1-optimal threshold
    collapses to flag-everything, and F1 lands at the algebraic all-positive value
    2(0.5)/(1+0.5) = 0.667. This is what made Amharic appear to 'gain' 34 F1 points.
    """
    rng = np.random.default_rng(0)
    n = 4000
    labels = np.concatenate([np.ones(n // 2, int), np.zeros(n // 2, int)])
    # Near-useless scores: the two classes are almost indistinguishable.
    scores = np.clip(rng.normal(0.5, 0.2, n) + 0.01 * labels, 0, 1)

    tau = tune_threshold(scores, labels, objective="f1")
    op = operating_point(scores, labels, tau)

    assert op.predicted_positive_rate > DEGENERATE_PPR_HIGH, "expected collapse to flag-everything"
    assert op.f1 == pytest.approx(2 / 3, abs=0.05), "expected the all-positive F1 plateau"
    assert is_degenerate(scores, tau), "the guard must catch exactly this case"


def test_fpr_budget_makes_flag_everything_inadmissible():
    """The reason D-011 switches the primary objective: a target-FPR budget cannot be
    satisfied by flagging everything, so the artifact cannot arise."""
    rng = np.random.default_rng(1)
    n = 4000
    labels = np.concatenate([np.ones(n // 2, int), np.zeros(n // 2, int)])
    scores = np.clip(rng.normal(0.5, 0.2, n) + 0.01 * labels, 0, 1)

    tau = tune_threshold(scores, labels, objective="target_fpr", target_fpr=0.05)
    op = operating_point(scores, labels, tau)

    assert op.fpr <= 0.05 + 1e-9
    assert not is_degenerate(scores, tau)


def test_realistic_prevalence_removes_the_incentive_to_flag_everything():
    """The artifact is generated by the 50/50 balance (R-13). At 5% prevalence, flagging
    everything scores F1 ~ 0.095 and is no longer attractive, so F1-tuning behaves sanely."""
    rng = np.random.default_rng(2)
    n_pos, n_neg = 200, 3800          # 5% prevalence
    labels = np.concatenate([np.ones(n_pos, int), np.zeros(n_neg, int)])
    scores = np.concatenate([
        np.clip(rng.normal(0.62, 0.15, n_pos), 0, 1),
        np.clip(rng.normal(0.45, 0.15, n_neg), 0, 1),
    ])

    all_positive_f1 = operating_point(scores, labels, 0.0).f1
    assert all_positive_f1 < 0.15, "all-positive should be unattractive at low prevalence"

    tau = tune_threshold(scores, labels, objective="f1")
    assert not is_degenerate(scores, tau)
