"""Generate the appendix from preserved artifacts.

Reviewer simulation #3 (R3.8) found the manuscript promising material "enumerated in the
supplementary material" that did not exist. Rather than delete the promise, we keep it and
generate the content from the same audit JSON the experiment actually used, so the appendix
cannot drift from what the code did.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

AUDIT = REPO_ROOT / "data" / "processed" / "sib200_audit.json"
THEORY = REPO_ROOT / "results" / "tables" / "negatives_theory_vs_observed.csv"
OUT = REPO_ROOT / "manuscript" / "sections" / "appendix.tex"


def main() -> int:
    import pandas as pd

    if not AUDIT.exists():
        print(f"missing {AUDIT}; run scripts/audit_sib200.py first")
        return 1
    audit = json.loads(AUDIT.read_text(encoding="utf-8"))

    excluded = audit["excluded_configs"]
    mismatch = {r["config"]: r["n"] for r in audit["row_count_mismatch_configs"]}

    lines = [
        "% GENERATED by scripts/make_appendix.py -- do not edit by hand.",
        "",
        r"\section{Excluded SIB-200 configurations}",
        r"\label{app:excluded}",
        "",
        # Escape the reference language name too: `eng_Latn` contains an underscore, which
        # is math-mode-only and aborts the build with a misleading error. The table entries
        # were escaped from the start; this inline mention was not.
        f"The parallel-corpus arm requires row alignment with the reference language "
        f"(\\texttt{{{audit['reference_language'].replace('_', chr(92) + '_')}}}, "
        f"{audit['reference_n']} rows). Of "
        f"{audit['n_configs']} language configurations, "
        f"{audit['n_parallel_aligned']} are aligned and enter the arm; "
        f"{len(excluded)} are excluded. Table~\\ref{{tab:excluded}} lists the exclusions in "
        f"full rather than summarising them, so that the arm's composition is fully "
        f"specified.",
        "",
        r"\begin{table}[!t]",
        r"\centering",
        r"\small",
        r"\caption{SIB-200 configurations excluded from the parallel-corpus arm, with row "
        r"counts where these differ from the reference. Several are severely truncated.}",
        r"\label{tab:excluded}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"Configuration & Rows (reference: " + str(audit["reference_n"]) + r") \\",
        r"\midrule",
    ]

    for cfg in sorted(excluded):
        n = mismatch.get(cfg)
        n_str = str(n) if n is not None else "not row-aligned"
        cfg_tex = cfg.replace("_", r"\_")
        lines.append(rf"\texttt{{{cfg_tex}}} & {n_str} \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]

    if THEORY.exists():
        df = pd.read_csv(THEORY)
        lines += [
            r"\section{Calibration regimes and the binomial prediction}",
            r"\label{app:regimes}",
            "",
            r"Table~\ref{tab:regimes} lists every calibration regime reported in the paper "
            r"alongside $m = \alpha\,n_{\mathrm{neg}}$, the expected number of permitted "
            r"false positives, and the observed budget-violation rate. The rule "
            r"$m \ge 10$ separates the regimes that work from those that do not.",
            "",
            # The full statement of the rule's status lives beside the recommendation in the
            # Discussion, where a practitioner meets it; repeating it here duplicated four
            # sentences almost verbatim across two sections.
            r"These 18 regimes are the entire evidence base for the threshold of $10$, so the "
            r"constant is an in-sample summary rather than an externally validated one; "
            r"Section~\ref{sec:guidance} states what does and does not transfer.",
            "",
            r"\begin{table}[!t]",
            r"\centering",
            r"\small",
            r"\caption{Expected permitted false positives $m$ against observed failure, "
            # No \textsc: ieeeaccess.cls's caption font (formata) has no small-caps shape, so
            # it raises a substitution warning on every build.
            r"across all calibration regimes. The Source column identifies the "
            r"experiment each regime comes from: the two rows at $\alpha = 0.05$ for full "
            r"per-language calibration are the toxicity arm (EXP-002) and the budget sweep "
            r"(EXP-007), which differ slightly in calibration-set size. "
            # No p-value here: 12 of the 18 regimes are nested few-label subsamples of one
            # experiment, so an 18-observation test would be anti-conservative. The clustered
            # figure is reported in the body instead.
            r"Spearman $\rho = -0.823$ across all 18 rows, which are not independent; see "
            r"Section~\ref{sec:negatives} for the clustered estimate.}",
            r"\label{tab:regimes}",
            r"\begin{adjustbox}{max width=\columnwidth}",
            r"\begin{tabular}{llrrrr}",
            r"\toprule",
            r"Regime & Source & $\alpha$ & $n_{\mathrm{neg}}$ & $m$ & Violation \\",
            r"\midrule",
        ]
        for _, r in df.iterrows():
            regime = str(r["regime"]).replace("_", r"\_").replace("%", r"\%")
            lines.append(
                rf"{regime} & {r['source']} & {r['alpha']:.2f} & {r['n_neg']:.0f} & "
                rf"{r['expected_fp']:.2f} & {r['observed_violation_rate']:.3f} \\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{adjustbox}",
                  r"\end{table}", ""]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"appendix: {len(excluded)} excluded configs, "
          f"{len(df) if THEORY.exists() else 0} regimes -> {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

