"""Copy generated figures into the manuscript tree and emit their LaTeX float blocks.

FIGURE CONSTITUTION requires every figure to be regenerable and to carry its
caption alongside its source data. Writing the float blocks by hand would break that chain:
the caption in the paper could drift from the caption in the manifest, and nothing would
detect it. This script is therefore the single place where a figure becomes part of the
manuscript, and it takes both the file and the caption from the manifest.

Reviewer simulation #3 (R3.1) found the manuscript contained NO figures at all and one
dangling `\ref{fig:tradeoff}`. This closes that.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "results" / "figures" / "figure_manifest.json"
DEST = REPO_ROOT / "manuscript" / "figures"
OUT_TEX = REPO_ROOT / "manuscript" / "sections" / "figures.tex"

#: figure key -> (LaTeX label, single/double column). Two-column floats use figure* so wide
#: panels are not crushed into one column of the IEEE Access layout.
LAYOUT = {
    "fig1_threshold_divergence": ("fig:divergence", False),
    # fig2_fpr_budget_violation was removed: it plotted the same aggregation of the same rows
    # of EXP-002 as the left panel of fig2b (same strategy order, same means, same standard
    # errors, same value labels, same budget line), so it carried no information the paired
    # figure does not. Section V-A now cites that panel directly.
    "fig2b_strategy_tradeoff": ("fig:tradeoff", True),
    "fig3_label_efficiency": ("fig:labeleff", False),
    "fig4_auroc_vs_gap": ("fig:auroc", False),
    "fig5_degeneracy_vs_prevalence": ("fig:degeneracy", False),
}

#: Figures whose float block is written to its own file, so that 05_results.tex can declare it
#: beside the paragraph that discusses it instead of leaving it in the trailing block that
#: main.tex inputs after the whole Results section.
#:
#: A float can never be typeset earlier than the point at which it is declared. Emitting every
#: figure into one trailing block therefore set a floor on how early any figure could appear:
#: Figures 1 and 2 came out seven and eight pages after the discussion that needs them, in the
#: Discussion section rather than in Results, and three figures collided on one page that
#: carried three lines of body text. Splitting only these two removes that floor.
#:
#: The emitted block, caption and label are identical whichever file they land in, so the
#: caption still comes from the manifest and still cannot drift. Figures not listed here keep
#: the previous behaviour.
INLINE = {"fig1_threshold_divergence", "fig2b_strategy_tradeoff"}


def _escape_latex(text: str) -> str:
    """Escape LaTeX special characters in caption prose.

    Captions are written as plain English in the figure manifest and must survive being
    dropped into a .tex file. Underscores are the trap: strategy names such as
    `source_global` appear verbatim in captions, and an unescaped `_` is a math-mode-only
    character that aborts the build with a misleading "Missing $ inserted" error pointing at
    the wrong place. Backslash is replaced first so the replacements are not themselves
    re-escaped.
    """
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
        ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
        ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def main() -> int:
    if not MANIFEST.exists():
        print(f"missing {MANIFEST}; run scripts/make_figures.py first")
        return 1

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    DEST.mkdir(parents=True, exist_ok=True)

    blocks: list[str] = [
        "% GENERATED by scripts/sync_manuscript_figures.py -- do not edit by hand.",
        "% Captions are taken from results/figures/figure_manifest.json so that the caption",
        "% in the paper cannot drift from the caption recorded with the source data.",
        "%",
        "% This file holds the figures that are declared after the Results section. Figures",
        "% listed in the script's INLINE set are written to sections/fig_<name>.tex instead and",
        "% declared next to the paragraph that discusses them.",
        "",
    ]
    inline_files: list[Path] = []

    for entry in manifest:
        key = entry["figure"]
        if key not in LAYOUT:
            print(f"  SKIP {key}: no layout entry")
            continue
        label, wide = LAYOUT[key]

        pdf = REPO_ROOT / next(p for p in entry["exports"] if p.endswith(".pdf"))
        shutil.copy2(pdf, DEST / pdf.name)

        env = "figure*" if wide else "figure"
        width = "\\textwidth" if wide else "\\columnwidth"
        caption = _escape_latex(entry["caption"])

        block = [
            f"\\begin{{{env}}}[!t]",
            "\\centering",
            f"\\includegraphics[width={width}]{{{pdf.stem}}}",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
            f"\\end{{{env}}}",
        ]
        kind = "2-col" if wide else "1-col"

        if key in INLINE:
            out = OUT_TEX.parent / f"fig_{label.split(':', 1)[1]}.tex"
            out.write_text(
                "% GENERATED by scripts/sync_manuscript_figures.py -- do not edit by hand.\n"
                f"% Float block for {label}. Kept in its own file so that 05_results.tex can\n"
                "% declare it beside the paragraph that discusses it; a float cannot be typeset\n"
                "% earlier than the point at which it is declared. The caption is taken from\n"
                "% results/figures/figure_manifest.json, exactly as for the trailing block.\n"
                + "\n".join(block) + "\n",
                encoding="utf-8")
            inline_files.append(out)
            print(f"  OK   {key} -> {label} ({kind}, inline: {out.name})")
        else:
            blocks.extend(block)
            blocks.append("")
            print(f"  OK   {key} -> {label} ({kind})")

    OUT_TEX.write_text("\n".join(blocks) + "\n", encoding="utf-8")
    print(f"\n{len(manifest)} figures -> {OUT_TEX.relative_to(REPO_ROOT)}"
          + "".join(f"\n{'':17}+ {p.relative_to(REPO_ROOT)}" for p in inline_files))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
